//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semanticer.TextAnalyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Semanticer.TextAnalyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zakończyłem analizę.
        /// </summary>
        internal static string EndAnalitycs {
            get {
                return ResourceManager.GetString("EndAnalitycs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zakończono zaminanę słowa na synonim.
        /// </summary>
        internal static string EndChangeSynonim {
            get {
                return ResourceManager.GetString("EndChangeSynonim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zakończyłem pobieranie synonimów z bazy danych.
        /// </summary>
        internal static string EndGetSynonim {
            get {
                return ResourceManager.GetString("EndGetSynonim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zakończono rozbijanie komentarza na pojedyńcze słowa.
        /// </summary>
        internal static string EndGetWordComments {
            get {
                return ResourceManager.GetString("EndGetWordComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zakończyłem normalizację słowa.
        /// </summary>
        internal static string EndNormalizationWord {
            get {
                return ResourceManager.GetString("EndNormalizationWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zakończyłem normalizowanie słów w komentarzu.
        /// </summary>
        internal static string EndNormalizationWords {
            get {
                return ResourceManager.GetString("EndNormalizationWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zakończono dodawanie słów do chmury.
        /// </summary>
        internal static string EndSetCloud {
            get {
                return ResourceManager.GetString("EndSetCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zakończono zapisywanie słów w słowniku.
        /// </summary>
        internal static string EndSetDictionary {
            get {
                return ResourceManager.GetString("EndSetDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rozpoczynam analizę .
        /// </summary>
        internal static string StartAnalitycs {
            get {
                return ResourceManager.GetString("StartAnalitycs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rozpoczynam zamianę slowa na synonim.
        /// </summary>
        internal static string StartChangeSynonim {
            get {
                return ResourceManager.GetString("StartChangeSynonim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rozpoczynam pobieranie synonimów z bazy danych.
        /// </summary>
        internal static string StartGetSynonim {
            get {
                return ResourceManager.GetString("StartGetSynonim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rozpoczynam rozbijanie komentarza na pojedyńcze słowa.
        /// </summary>
        internal static string StartGetWordFromComent {
            get {
                return ResourceManager.GetString("StartGetWordFromComent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rozpoczynam normalizowanie słowa.
        /// </summary>
        internal static string StartNormalizationWord {
            get {
                return ResourceManager.GetString("StartNormalizationWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rozpoczynam normalizację słów w komentarzu.
        /// </summary>
        internal static string StartNormalizationWords {
            get {
                return ResourceManager.GetString("StartNormalizationWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rozpoczynam dodawanie słów do chmury.
        /// </summary>
        internal static string StartSetCloud {
            get {
                return ResourceManager.GetString("StartSetCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rozpoczynam zapisywanie słów w słowniku.
        /// </summary>
        internal static string StartSetDictionary {
            get {
                return ResourceManager.GetString("StartSetDictionary", resourceCulture);
            }
        }
    }
}
