namespace Semanticer.Common.Enums
{
    public enum LoggerEventType
    {
        DownloadStart = 1,
        DownloadFinished = 2,
        AnalyzeStart = 3,
        AnalyzeFinished = 4,
        PostIndexingStart = 5,
        PostIndexingFinished = 6,
        ProfilePostsDownloadStarted = 7,
        ProfilePostsDownloadFinished = 8,
        ProfilePostsResponsesDownloadStarted = 9,
        ProfilePostsResponsesDownloadFinished = 10,
        PostsAuthorsDownloadStarted = 11,
        PostsAuthorsDownloadFinished = 12,
        PostKeywordsSearchStart = 13,
        PostKeywordsSearchFinished = 14,
        ProfileLookUpStart = 15,
        ProfileLookUpFinished = 16,
        PostSematicCalcutationStart = 17,
        PostSematicCalcutationStop = 18,
        ClassifierTrainingStart = 19,
        ClassifierTrainingStop = 20,
        StreamProgress = 21,
        LoadClassifierStart = 23,
        LoadClassifierStop = 24,
        AuthorsSaveStart = 25,
        AuthorsSaveDone = 26,
        PostsSaveStart = 27,
        PostsSaveDone = 28,
        PostsPackageIndexingStart = 29,
        PostsPackageIndexingDone = 30,
        PostAgregationStart = 31,
        PostAgregationDone = 32,
    }
}